import { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
    en: {
        // Sidebar
        dashboard: 'Dashboard',
        inventory: 'IT Support Inventory',
        phones: 'Phone Management',
        history: 'History',
        settings: 'Settings',
        logout: 'Logout',

        // Tutorial
        'tutorial.sidebarTitle': 'Sidebar Navigation',
        'tutorial.sidebarDesc': 'Use this menu to navigate between different modules.',
        'tutorial.dashboardDesc': 'Your main command center. View key statistics and shortcuts.',
        'tutorial.inventoryDesc': 'Manage all your products, stock levels, and locations.',
        'tutorial.searchDesc': 'Quickly find any product, employee, or log.',
        'tutorial.settingsDesc': 'Configure users, categories, and system preferences.',
        'tutorial.next': 'Next',
        'tutorial.prev': 'Previous',
        'tutorial.done': 'Finish',
        'tutorial.addItemTitle': 'Add New Item',
        'tutorial.addItemDesc': 'Click here to register new equipment into your inventory.',
        'tutorial.addPCDesc': 'Register a new loaner laptop here.',
        'tutorial.loanTableDesc': 'View status of all loaner PCs. Check overdue items.',
        'tutorial.assignPCDesc': 'Click the green arrow to assign this PC to a user.',
        'tutorial.inventoryActions': 'Add products or manage categories here.',

        'tutorial.productsTitle': 'Product List',
        'tutorial.productsDesc': 'List of all your equipment. Click to edit or assign.',
        'tutorial.dashboardStats': 'Key metrics about your inventory and users.',
        'tutorial.chartsTitle': 'Analytics',
        'tutorial.chartsDesc': 'Visual representation of stock distribution and movements.',



        // Dashboard
        dashboardTitle: 'Dashboard',
        dashboardSubtitle: 'Overview of your IT inventory',
        totalItems: 'Total Items',
        lowStockAlerts: 'Low Stock Alerts',
        categories: 'Categories',
        stockByCategory: 'Stock by Category',
        distribution: 'Distribution',
        recentActivity: 'Recent Activity',
        viewAll: 'View All',
        addItem: 'Add Item',
        noRecentActivity: 'No recent activity',

        // Inventory
        inventoryTitle: 'Inventory Management',
        searchInventory: 'Search in selected category...',
        allItems: 'All Items',
        allProducts: 'All Products',
        noProducts: 'No products found in this category.',
        lowStock: 'Low Stock',
        addNewItem: 'Add New Item',
        fillDetails: 'Fill in the details below',
        name: 'Name',
        category: 'Category',
        quantity: 'Quantity',
        minQuantity: 'Min Quantity',
        location: 'Location',
        description: 'Description',
        cancel: 'Cancel',
        selectCategory: 'Select Category',
        placeholderName: 'e.g. Dell Latitude 5520',
        placeholderLocation: 'e.g. Building A, Floor 2',
        placeholderDescription: 'Optional notes...',
        removeStock: 'Remove from Stock',
        recipientName: 'Recipient Name',
        placeholderRecipient: 'e.g. John Doe',
        confirmRemove: 'Confirm Removal',
        reference: 'Reference',
        placeholderReference: 'e.g. INC0045254 - PRT4541',
        referenceHint: 'Enter ticket number (INC...) and PRT to identify the PC/user.',
        editProduct: 'Edit Product',
        saveChanges: 'Save Changes',
        deleteProduct: 'Delete Product',

        // History
        activityTimeline: 'Activity Timeline',
        searchLogs: 'Search logs...',
        allActivity: 'All Activity',
        newItems: 'New Items',
        stockUpdates: 'Stock Updates',
        noHistoryFound: 'No history found matching your filters.',

        // Settings
        settingsTitle: 'Settings',
        appearance: 'Appearance',
        userManagement: 'Hotliner Management',
        myAccount: 'My Account',
        interfaceTheme: 'Interface Theme',
        chooseTheme: 'Choose a theme that fits your workspace.',
        lightMode: 'Light Mode',
        semiDark: 'Semi Dark',
        darkMode: 'Dark Mode',
        language: 'Language',
        chooseLanguage: 'Select your preferred language.',
        createUser: 'Create User',
        addAccessAccount: 'Add a new access account for a team member.',
        username: 'Username',
        password: 'Password',
        roleAccess: 'Role Access',
        hotliner: 'Hotliner (Standard)',
        admin: 'Team Leader (Admin)',
        createAccount: 'Create Account',
        currentUsers: 'Current Users',
        myProfile: 'My Profile',
        role: 'Role',
        accessDenied: 'You do not have permission to view this section.',
        userAdded: 'User added successfully',
        categoriesManagement: 'Categories',
        addCategory: 'Add Category',
        addCategoryDesc: 'Create a new product category.',
        categoryName: 'Category Name',
        placeholderCategory: 'e.g. Monitors',
        existingCategories: 'Existing Categories',
        noCategories: 'No categories yet.',
        confirmDeleteCategory: 'Delete this category? (Only empty categories can be deleted)',

        // Employees
        employeesManagement: 'Employees',
        addEmployee: 'Add Employee',
        addEmployeeDesc: 'Add an employee for equipment tracking.',
        employeeName: 'Full Name',
        employeeEmail: 'Email',
        employeeDepartment: 'Department',
        placeholderEmployeeName: 'e.g. John Doe',
        placeholderEmployeeEmail: 'e.g. john@company.com',
        placeholderDepartment: 'e.g. IT Support',
        existingEmployees: 'Employees List',
        noEmployees: 'No employees yet.',
        confirmDeleteEmployee: 'Delete this employee?',
        selectEmployee: 'Select Employee',
        employeePassword: 'Password',
        placeholderEmployeePassword: 'Password for dashboard access',
        employeePasswordHint: 'If set, employee can login with their email to view dashboard only.',
        optional: 'optional',
        editEmployee: 'Edit Employee',
        updateEmployee: 'Update Employee',


        // Search
        searchGlobal: 'Search products, employees, logs...',
        noResults: 'No results found',

        // Security
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm Password',
        passwordChanged: 'Password changed successfully',
        passwordMismatch: 'Passwords do not match',

        editUser: 'Edit User',
        updateUser: 'Update User',

        // Reports
        reports: 'Reports',
        selectPeriod: 'Select Period',
        startDate: 'Start Date',
        endDate: 'End Date',
        print: 'Print',
        downloadPDF: 'Download PDF',

        // Loan PC
        restore: 'Restore',
        remaster: 'Remaster',
        remastering: 'Remastering',
        confirmRestore: 'Restore this PC to available status?',
        confirmRemaster: 'Toggle remastering status?',
        entries: 'Entries',
        exits: 'Exits',
        operations: 'Operations',
        operationsDetail: 'Operations Detail',
        date: 'Date',
        action: 'Action',
        details: 'Details',
        user: 'User',
        noDataPeriod: 'No data for this period',

        // Loan PCs
        loanPCManagement: 'Loan PC Management',
        loanPC: 'Loan PC',
        addPC: 'Add PC',
        searchPC: 'Search PC...',
        allStatuses: 'All Statuses',
        available: 'Available',
        loaned: 'Loaned',
        outOfService: 'Out of Service',
        overdue: 'Overdue',
        serialNumber: 'Serial Number',
        model: 'Model',
        status: 'Status',
        assignedTo: 'Assigned To',
        loanDate: 'Loan Date',
        dueDate: 'Due Date',
        actions: 'Actions',
        returnDate: 'Return Date',
        loanHistory: 'Loan History',
        assignPC: 'Assign PC',
        returnPC: 'Return PC',
        borrowerName: 'Borrower Name',
        durationDays: 'Duration (Days)',
        reason: 'Reason',
        returnNotes: 'Return Notes',
        returnCondition: 'Return Condition',
        goodCondition: 'Good Condition',
        damaged: 'Damaged',
        confirmLoan: 'Confirm Loan',
        confirmReturn: 'Confirm Return',
        pcAdded: 'PC added successfully',
        loanRegistered: 'Loan registered successfully',
        returnRegistered: 'Return registered successfully',

        // PRT History
        fullHistoryFor: 'Full history for',
        searchPRTorUser: 'Search PRT number or user',
        enterPRT: 'Enter PRT (e.g. PRT3150)',
        search: 'Search',
        events: 'Events',
        timeline: 'Timeline',
        noHistoryFor: 'No history found for',

        // Dashboard Widgets
        stockDistribution: 'Stock Distribution',
        quickActions: 'Quick Actions',
        statistics: 'Statistics',
        customize: 'Customize',
        resetLayout: 'Reset Layout',
        saveLayout: 'Save Layout',

        // Danger Zone
        dangerZone: 'Danger Zone',
        dangerZoneDesc: 'Irreversible destructive actions. Handle with care.',
        resetDatabase: 'Reset Database',
        resetEmployees: 'Reset Employees',
        resetDatabaseDesc: 'Deletes all inventory, history, loans, and logs. Admin accounts are preserved.',
        resetEmployeesDesc: 'Deletes all employee accounts only.',
        btnResetDatabase: 'Reset DB (Except Admin)',
        btnResetEmployees: 'Reset Employees',
        alertResetDB1: 'WARNING: You are about to wipe the ENTIRE database (Inventory, Logs, Loans, etc.).\n\nThis action is irreversible!\n\nDo you really want to continue?',
        alertResetDB2: 'Are you ABSOLUTELY sure? This will delete all inventory.',
        alertResetEmp1: 'WARNING: You are going to delete ALL employees.\n\nThis action is irreversible.\n\nContinue?',
        resetSuccessDB: 'Database reset successfully (Admin account preserved).',
        resetSuccessEmp: 'All employees have been deleted.',
        errorReset: 'Error during reset.',

        // Common
        back: 'Back',
        loading: 'Loading...',

        // Categories (Database Keys)
        'cat_PC': 'PC',
        'cat_Laptop': 'Laptop',
        'cat_Screen': 'Monitor',
        'cat_Keyboard': 'Keyboard',
        'cat_Mouse': 'Mouse',
        'cat_Battery': 'Battery',
        'cat_Charger': 'Charger',
        'cat_Adapter': 'Adapter',
        'cat_Cleaning': 'Cleaning Kit',
        'cat_Cables': 'Cables',
        'cat_Projector': 'Projector',
        'cat_Privacy Filter': 'Privacy Filter',
        'cat_Station d\'accueil': 'Docking Station',
        'cat_Station d\'accueil': 'Docking Station', // Duplicate safe-guard if needed or just handle key
        'cat_Audio': 'Audio',
        'cat_Composants': 'Components',
        'cat_Périphériques': 'Peripherals',
        'cat_Stockage': 'Storage',
        'cat_Réseau': 'Network',
        'cat_Imprimante': 'Printer',
        'cat_Consommable': 'Consumable',
        'cat_Logiciel': 'Software',
        'cat_Licence': 'License',
        'cat_Autre': 'Other',
    },
    fr: {
        // Sidebar
        dashboard: 'Tableau de bord',
        inventory: 'Support Informatique',
        phones: 'Téléphonie',
        history: 'Historique',
        settings: 'Paramètres',
        logout: 'Déconnexion',

        // Tutorial
        'tutorial.sidebarTitle': 'Navigation Latérale',
        'tutorial.sidebarDesc': 'Utilisez ce menu pour naviguer entre les différents modules.',
        'tutorial.dashboardDesc': 'Votre centre de commande principal. Visualisez les statistiques clés.',
        'tutorial.inventoryDesc': 'Gérez tous vos produits, niveaux de stock et emplacements.',
        'tutorial.searchDesc': 'Trouvez rapidement n\'importe quel produit, employé ou log.',
        'tutorial.settingsDesc': 'Configurez les utilisateurs, catégories et préférences du système.',
        'tutorial.next': 'Suivant',
        'tutorial.prev': 'Précédent',
        'tutorial.done': 'Terminer',
        'tutorial.addItemTitle': 'Ajouter un Article',
        'tutorial.addItemDesc': 'Cliquez ici pour enregistrer du nouveau matériel.',
        'tutorial.addPCDesc': 'Enregistrez un nouveau PC de prêt ici.',
        'tutorial.loanTableDesc': 'Voyez l\'état de tous les PC. Vérifiez les retards.',
        'tutorial.assignPCDesc': 'Cliquez sur la flèche verte pour prêter ce PC.',


        'tutorial.inventoryActions': 'Ajoutez des produits ou gérez les catégories ici.',
        'tutorial.productsDesc': 'Liste de tout votre matériel. Cliquez pour modifier ou assigner.',
        'tutorial.dashboardStats': 'Indicateurs clés sur votre inventaire.',
        'tutorial.chartsTitle': 'Analytique',
        'tutorial.chartsDesc': 'Représentation visuelle de la distribution du stock.',
        'tutorial.productsTitle': 'Liste des Produits',

        'tutorial.historyFilters': 'Filtrer par type d\'action (Ajout, Mise à jour).',
        'tutorial.historySearch': 'Rechercher une action ou un utilisateur spécifique.',
        'tutorial.historyTimeline': 'Vue chronologique de toutes les actions.',

        'tutorial.reportsDate': 'Sélectionnez la période pour le rapport.',
        'tutorial.reportsStats': 'Détail des entrées et sorties sur la période.',

        // Loan PC
        restore: 'Réparé / En Service',
        remaster: 'Remasterisation',
        remastering: 'En Remasterisation',
        confirmRestore: 'Remettre ce PC en service (Disponible) ?',
        confirmRemaster: 'Activer/Désactiver le mode remasterisation ?',
        'tutorial.reportsTable': 'Liste complète des opérations exportable en PDF.',

        // Dashboard
        dashboardTitle: 'Tableau de bord',
        dashboardSubtitle: 'Vue d\'ensemble de votre inventaire IT',
        totalItems: 'Total Articles',
        lowStockAlerts: 'Alertes Stock Bas',
        categories: 'Catégories',
        stockByCategory: 'Stock par Catégorie',
        distribution: 'Répartition',
        recentActivity: 'Activité Récente',
        viewAll: 'Voir Tout',
        addItem: 'Ajouter',
        noRecentActivity: 'Aucune activité récente',

        // Dashboard Widgets & Presets
        stockEvolution: 'Évolution du stock',
        topProducts: 'Top produits sortants',
        lowStockItems: 'Articles Stock Faible',
        todayActivity: 'Activité du Jour',
        loanedPC: 'PC en prêt',
        days: 'jours',
        noData: 'Pas de données',
        product: 'Produit',
        stock: 'Stock',
        min: 'Min',
        none: 'Aucun',

        // Views
        defaultView: 'Vue par défaut',
        adminView: 'Vue Admin',
        stockView: 'Vue Stock',
        activityView: 'Vue Activité',
        availableWidgets: 'Widgets disponibles',
        layoutSaved: 'Dashboard sauvegardé !',

        // Filters
        from: 'Du',
        to: 'Au',
        allCategory: 'Toutes',
        status: 'Statut',
        all: 'Tous',
        normalStock: 'Stock normal',
        apply: 'Appliquer',

        // Inventory
        inventoryTitle: 'Gestion de l\'Inventaire',
        searchInventory: 'Rechercher dans la catégorie...',
        allItems: 'Tous les Articles',
        allProducts: 'Tous les Produits',
        noProducts: 'Aucun produit trouvé dans cette catégorie.',
        lowStock: 'Stock Bas',
        addNewItem: 'Ajouter un Article',
        fillDetails: 'Remplissez les informations ci-dessous',
        name: 'Nom',
        category: 'Catégorie',
        quantity: 'Quantité',
        minQuantity: 'Quantité Min',
        location: 'Emplacement',
        description: 'Description',
        cancel: 'Annuler',
        selectCategory: 'Choisir une Catégorie',
        placeholderName: 'ex. Dell Latitude 5520',
        placeholderLocation: 'ex. Bâtiment A, Étage 2',
        placeholderDescription: 'Notes optionnelles...',
        removeStock: 'Retirer du Stock',
        recipientName: 'Nom du Bénéficiaire',
        placeholderRecipient: 'ex. Jean Dupont',
        confirmRemove: 'Confirmer le Retrait',
        reference: 'Référence',
        placeholderReference: 'ex. INC0045254 - PRT4541',
        referenceHint: 'Entrez le numéro de ticket (INC...) et le PRT pour identifier le PC/utilisateur.',
        editProduct: 'Modifier le Produit',
        saveChanges: 'Enregistrer',
        deleteProduct: 'Supprimer le Produit',

        // History
        activityTimeline: 'Chronologie d\'Activité',
        searchLogs: 'Rechercher dans les logs...',
        allActivity: 'Toute l\'Activité',
        newItems: 'Nouveaux Articles',
        stockUpdates: 'Mises à jour Stock',
        noHistoryFound: 'Aucun historique trouvé.',

        // Settings
        settingsTitle: 'Paramètres',
        appearance: 'Apparence',
        userManagement: 'Gestion des Hotliners',
        myAccount: 'Mon Compte',
        interfaceTheme: 'Thème de l\'Interface',
        chooseTheme: 'Choisissez un thème adapté à votre espace de travail.',
        lightMode: 'Mode Clair',
        semiDark: 'Semi Sombre',
        darkMode: 'Mode Sombre',
        language: 'Langue',
        chooseLanguage: 'Sélectionnez votre langue préférée.',
        createUser: 'Créer un Utilisateur',
        addAccessAccount: 'Ajouter un compte d\'accès pour un membre de l\'équipe.',
        username: 'Nom d\'utilisateur',
        password: 'Mot de passe',
        roleAccess: 'Niveau d\'Accès',
        hotliner: 'Hotliner (Standard)',
        admin: 'Chef d\'équipe (Admin)',
        createAccount: 'Créer le Compte',
        currentUsers: 'Utilisateurs Actuels',
        myProfile: 'Mon Profil',
        role: 'Rôle',
        accessDenied: 'Vous n\'avez pas la permission de voir cette section.',
        userAdded: 'Utilisateur ajouté avec succès',
        categoriesManagement: 'Catégories',
        addCategory: 'Ajouter une Catégorie',
        addCategoryDesc: 'Créer une nouvelle catégorie de produit.',
        categoryName: 'Nom de la Catégorie',
        placeholderCategory: 'ex. Écrans',
        existingCategories: 'Catégories Existantes',
        noCategories: 'Aucune catégorie pour le moment.',
        confirmDeleteCategory: 'Supprimer cette catégorie ? (Seules les catégories vides peuvent être supprimées)',

        // Employees
        employeesManagement: 'Employés',
        addEmployee: 'Ajouter un Employé',
        addEmployeeDesc: 'Ajouter un employé pour le suivi du matériel.',
        employeeName: 'Nom Complet',
        employeeEmail: 'Email',
        employeeDepartment: 'Département',
        placeholderEmployeeName: 'ex. Jean Dupont',
        placeholderEmployeeEmail: 'ex. jean@entreprise.com',
        placeholderDepartment: 'ex. Support IT',
        existingEmployees: 'Liste des Employés',
        noEmployees: 'Aucun employé pour le moment.',
        confirmDeleteEmployee: 'Supprimer cet employé ?',
        selectEmployee: 'Sélectionner un Employé',
        employeePassword: 'Mot de passe',
        placeholderEmployeePassword: 'Mot de passe pour accès tableau de bord',
        employeePasswordHint: 'Si défini, l\'employé peut se connecter avec son email pour voir le tableau de bord.',

        optional: 'optionnel',
        editEmployee: 'Modifier l\'Employé',
        updateEmployee: 'Mettre à jour',


        // Search
        searchGlobal: 'Rechercher produits, employés, logs...',
        noResults: 'Aucun résultat trouvé',

        // Security
        changePassword: 'Changer le Mot de Passe',
        currentPassword: 'Mot de Passe Actuel',
        newPassword: 'Nouveau Mot de Passe',
        confirmPassword: 'Confirmer le Mot de Passe',
        passwordChanged: 'Mot de passe changé avec succès',
        passwordMismatch: 'Les mots de passe ne correspondent pas',

        editUser: 'Modifier Utilisateur',
        updateUser: 'Mettre à jour',

        // Reports
        reports: 'Rapports',
        selectPeriod: 'Sélectionner la période',
        startDate: 'Date de début',
        endDate: 'Date de fin',
        print: 'Imprimer',
        downloadPDF: 'Télécharger PDF',
        entries: 'Entrées',
        exits: 'Sorties',
        operations: 'Opérations',
        operationsDetail: 'Détail des opérations',
        date: 'Date',
        action: 'Action',
        details: 'Détails',
        user: 'Utilisateur',
        noDataPeriod: 'Aucune donnée pour cette période',

        // Loan PCs
        loanPCManagement: 'Gestion Prêts PC',
        loanPC: 'PC de Prêt',
        addPC: 'Ajouter un PC',
        searchPC: 'Rechercher un PC...',
        allStatuses: 'Tous les statuts',
        available: 'Disponible',
        loaned: 'Prêté',
        outOfService: 'Hors Service',
        overdue: 'En retard',
        serialNumber: 'Numéro Série',
        model: 'Modèle',
        // status: 'Statut', // Duplicate removed
        assignedTo: 'Assigné à',
        loanDate: 'Date Prêt',
        dueDate: 'Date Retour Prévue',
        actions: 'Actions',
        returnDate: 'Retour le',
        loanHistory: 'Historique des prêts',
        assignPC: 'Assigner un PC',
        returnPC: 'Retourner un PC',
        borrowerName: 'Nom de l\'emprunteur',
        durationDays: 'Durée (Jours)',
        reason: 'Raison',
        returnNotes: 'Notes de retour',
        returnCondition: 'Condition au retour',
        goodCondition: 'Bon état',
        damaged: 'Endommagé',
        confirmLoan: 'Confirmer le prêt',
        confirmReturn: 'Confirmer le retour',
        pcAdded: 'PC ajouté avec succès',
        loanRegistered: 'Prêt enregistré avec succès',
        returnRegistered: 'Retour enregistré avec succès',
        notReturned: 'Non restitué',

        // PRT History
        fullHistoryFor: 'Historique complet pour',
        searchPRTorUser: 'Rechercher un numéro PRT ou utilisateur',
        enterPRT: 'Entrer un numéro PRT (ex: PRT3150)',
        search: 'Rechercher',
        events: 'Événements',
        timeline: 'Chronologie',
        noHistoryFor: 'Aucun historique trouvé pour',

        // Dashboard Widgets
        stockDistribution: 'Distribution du Stock',
        quickActions: 'Actions Rapides',
        statistics: 'Statistiques',
        customize: 'Personnaliser',
        resetLayout: 'Réinitialiser',
        saveLayout: 'Sauvegarder',

        // Danger Zone
        dangerZone: 'Zone de Danger',
        dangerZoneDesc: 'Actions destructrices irréversibles. Manipuler avec précaution.',
        resetDatabase: 'Réinitialiser la BDD',
        resetEmployees: 'Réinitialiser les Employés',
        resetDatabaseDesc: 'Supprime tout l\'inventaire, l\'historique, les prêts, et les logs. Les comptes Admin sont conservés.',
        resetEmployeesDesc: 'Supprime tous les comptes employés uniquement.',
        btnResetDatabase: 'Réinitialiser BDD (Sauf Admin)',
        btnResetEmployees: 'Réinitialiser Employés',
        alertResetDB1: 'ATTENTION : Vous êtes sur le point d\'effacer TOUTE la base de données (Inventaire, Logs, Prêts, etc.).\n\nCette action est irréversible !\n\nVoulez-vous vraiment continuer ?',
        alertResetDB2: 'Êtes-vous ABSOLUMENT certain ? Cette action supprimera tout l\'inventaire.',
        alertResetEmp1: 'ATTENTION : Vous allez supprimer TOUS les employés.\n\nCette action est irréversible.\n\nContinuer ?',
        resetSuccessDB: 'La base de données a été réinitialisée avec succès (Compte Admin conservé).',
        resetSuccessEmp: 'Tous les employés ont été supprimés.',
        errorReset: 'Erreur lors de la réinitialisation.',

        // Common
        back: 'Retour',
        loading: 'Chargement...',
        generatedOn: 'Généré le',
        pdfReportTitle: 'Rapport d\'Inventaire',
        period: 'Période',

        // Categories (Database Keys)
        'cat_PC': 'PC',
        'cat_Laptop': 'PC Portable',
        'cat_Screen': 'Écran',
        'cat_Keyboard': 'Clavier',
        'cat_Mouse': 'Souris',
        'cat_Battery': 'Batterie',
        'cat_Charger': 'Chargeur',
        'cat_Adapter': 'Adaptateur',
        'cat_Cleaning': 'Kit Nettoyage',
        'cat_Cables': 'Câbles',
        'cat_Projector': 'Vidéoprojecteur',
        'cat_Privacy Filter': 'Filtre de Conf.',
        'cat_Station d\'accueil': 'Station d\'accueil',
        'cat_Audio': 'Audio',
        'cat_Composants': 'Composants',
        'cat_Périphériques': 'Périphériques',
        'cat_Stockage': 'Stockage',
        'cat_Réseau': 'Réseau',
        'cat_Imprimante': 'Imprimante',
        'cat_Consommable': 'Consommable',
        'cat_Logiciel': 'Logiciel',
        'cat_Licence': 'Licence',
        'cat_Autre': 'Autre',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'fr');

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => translations[language][key] || key;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
